//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafeCruisers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creamer
    {
        public int CreamerId { get; set; }
        public int OnePercentMilk { get; set; }
        public int TwoPercentMilk { get; set; }
        public int CoconutMilk { get; set; }
        public int Cream { get; set; }
        public int HeavyCream { get; set; }
        public int SkimMilk { get; set; }
        public int SoyMilk { get; set; }
        public int AlmondMilk { get; set; }
        public int WholeMilk { get; set; }
        public int OrderItemId { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
    }
}
