//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafeCruisers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sweetener
    {
        public int SweeterId { get; set; }
        public int Honey { get; set; }
        public int SugarInTheRaw { get; set; }
        public int Sugar { get; set; }
        public int Splenda { get; set; }
        public int Equal { get; set; }
        public int OrderItemId { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
    }
}
