//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KafeCruisers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syrup
    {
        public int SyrupId { get; set; }
        public int CaramelSyrup { get; set; }
        public int ChocolateSyrup { get; set; }
        public int PeppermintSyrup { get; set; }
        public int VanillaSyrup { get; set; }
        public int OrderItemId { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
    }
}
